using System;
using System.ComponentModel.DataAnnotations;

namespace Play.Catalog.Service.Dtos
{
	public record ItemDto(Guid Id, string Name, string Description, decimal Price, DateTimeOffset CreatedDate);

	// Dont need ID or created Date, will be automatically generated by service
	public record CreateItemDto([Required] string Name, string Description, [Range(1, 1000)] decimal Price);

	// Same memebers since updating existing
	public record UpdateItemDto([Required] string Name, string Description, [Range(1, 1000)] decimal Price);
}