using System;

namespace Play.Catalog.Service.Dtos
{
	public record ItemDto(Guid Id, string Name, string Description, decimal Price, DateTimeOffset CreatedDate);

	// Dont need ID or created Date, will be automatically generated by service
	public record CreateItemDto(string Name, string Description, decimal Price);

	// Same memebers atm
	public record UpdateItemDto(string Name, string Description, decimal Price);
}